// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f7824ccf-81e6-40f1-a5f8-bc29d7732e61",
    "aws_cognito_region": "eu-west-1",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "lot_lot",
            "alias": "$LATEST",
            "region": "eu-west-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamoaa1d2fb8-lot",
            "region": "eu-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api4dba6d21",
            "endpoint": "https://9qgss8zu9f.execute-api.eu-west-1.amazonaws.com/lot",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
